#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^poliscore:" ; then
    echo "Creating system group: poliscore"
    groupadd --system poliscore
fi

# add user
if ! getent passwd | grep -q "^poliscore:"; then
    echo "Creating poliscore system user"
    useradd --gid "poliscore" --system -m poliscore
fi

# build nodejs addons
cd "/usr/opt/poliscore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/poliscore/.poliscore/data"
chown -R poliscore:poliscore "/home/poliscore/.poliscore"

# start poliscore
if hash service 2> /dev/null; then
    service poliscore start || echo "poliscore could not be registered or started"
elif hash start 2> /dev/null; then
    start poliscore || echo "poliscore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "poliscore.service" && \
            systemctl start "poliscore.service"
    } || echo "poliscore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so poliscore could not be started'
fi
