#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service poliscore stop || echo "poliscore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "poliscore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "poliscore.service" || echo "poliscore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so poliscore could not be stopped"
fi
